### ISSUE TITLE
Установить необходимые инструменты для работы над проектом

### ISSUE THREAD

**Issue by mbyakow** [DmitriyTeterin/horsesharing#1]
Список инструментов — на странице урока.

**Comment by mbyakow** [comment]
@DmitriyTeterin в идеале перед тем как ты переводишь задачу в следующий статус нужно написать комментарий что именно было сделано. Это поможет твоему коллеге работать с задачей дальше (например, QA) или спустя время поднять историю по задаче и получить контекст. Это экономит время всем, так как если комментариев не будет, то человек придёт к тебе и будет задавать те же самые вопросы.

**Comment by DmitriyTeterin** [comment]
Установил: 
phpStorm
Brew
iTerm
Apache, MySQL, PhpMyAdmin
Postman
Docker

PHP 7.4 поставил, но включить не могу, работает 7.1
