### ISSUE TITLE
Рефакторинг кода

### ISSUE THREAD

**Issue by mbyakow** [DmitriyTeterin/horsesharing#4]
1. Вынести вывод информации о лошади в отдельный метод. На вход должен поступать массив с информацией о лошади. На выходе отдавать форматированную строку с информацией. Сама функция ничего не выводит, а только отдаёт строку.

У функции обязательно должны быть указаны тип входящего аргумента и тип возвращаемого значения.

2. Заменить все места, в которых выводилась информация о лошади, на вызов новой функции.

**Comment by DmitriyTeterin** [comment]
добавил метод. сделал коммит.
